Browser=chrome
URL=https://www.easycalculation.com
LoginURL=https://www.login.hiox.com/login?referrer=easycalculation.com
Email=binitsingh221712@gmail.com
Password=Binit@2003
ImplicitWait=10
PageLoadTime=30